M48
; DRILL file {KiCad 8.0.2-8.0.2-0~ubuntu22.04.1} date 2024-05-08T22:35:11+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-08T22:35:11+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2-8.0.2-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X4.7207Y-3.3559
X4.7207Y-3.4741
T2
X5.227Y-3.7871
T3
X4.754Y-2.308
X5.823Y-2.304
X5.825Y-3.59
M30
